### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by victorhazbun87** [heckpsi-lab/em-midori#10]
Hello,

I have some questions:

1. Is there an Api doc for this gem like Rails API docs?
2. Do you have more examples of how to use this gem?
3. At the current example at https://github.com/heckpsi-lab/em-midori/blob/master/example/route.rb#L37 it seems the router is in charge of responding, is this a good practice?
4. What is the layer of the system responsible for representing business data and logic for this gem?

Thanks! :)

**Comment by dsh0416** [comment]
1. I'm working on enriching API docs these days, which could be used before `v0.1.0` release.
2. This gem is still on the early development, examples are just showing the principles and APIs we want it to be. More practicable examples would be enriched after we stabilize the APIs.
3. Yes. The API we designed want to use route definition instead of writing API docs manually. https://github.com/heckpsi-lab/em-midori/blob/master/example/route.rb#L33 The route definition not only shows which `Controller` to use, but also how `request` and `response` are, all possible `error`s and how to handle them. With the help of middlewares, this definition could be further simplified.
4. `controller`s could be defined to deal with complex logic if you are building large projects. But if the logic is simple enough, you can also directly write it in router. em-midori provides the flexibility of which design pattern you want in your project.

**Comment by dsh0416** [comment]
API docs could be viewed at [here](http://www.rubydoc.info/gems/em-midori/0.0.9.1). But only 14.91% code are documented for now.
