### ISSUE TITLE
Chance for supporting for active record

### ISSUE THREAD

**Issue by eidge** [heckpsi-lab/em-midori#16]
Hi guys,

Congrats on the project!

I was wondering if once you have support for database connections if supporting ActiveRecord was an option or if there are other technical reasons preventing this.

Reason being, a well built application shouldn't be difficult to port from one of the existing frameworks (grape, sinatra, rails, etc) to Midori if we can have the same persistence layer.

Cheers

**Comment by dsh0416** [comment]
I've considered about supporting `ActiveRecord` or not for a few days. The answer is: **Yes**. This project would support `ActiveRecord` by designing an async driver as its adapter, then you could use `ActiveRecord` seamlessly.
But a small problem is that `ActiveRecord` using `Arel` to parse objects to AST, this process is pretty slow. Even if it would not cause the I/O block due to the async adapter, it still may infect some performance.
Using `ActiveRecord` or raw SQLs should depend on the actual needs of your project. What this project could do, is to provide as much tools as we can, and you could choose the most suitable one for yourself.
